#!/bin/bash

# HIT LAB - Multi-language Setup Guide

echo "=== HIT LAB Multilingual Website Setup ==="
echo ""
echo "✅ Структура створена:"
echo ""
echo "📁 Root Directory (/)"
echo "├── index.html          (Маршрутизація)"
echo "├── router.js           (JavaScript маршрутизація)"
echo "├── .htaccess           (Apache маршрутизація)"
echo "├── styles.css          (CSS для всіх мов)"
echo "├── js/"
echo "│   └── main.js         (JS для всіх мов)"
echo "├── images/             (Зображення)"
echo "├── ua/"
echo "│   └── index.html      (Українська версія)"
echo "├── pl/"
echo "│   └── index.html      (Польська версія)"
echo "└── en/"
echo "    └── index.html      (Англійська версія)"
echo ""
echo "🌍 Як працює:"
echo ""
echo "1. Користувач відвідує https://example.com/"
echo "2. index.html перевіряє мову браузера"
echo "3. Перенаправляє на /ua/, /pl/ або /en/"
echo "4. CSS та JS завантажуються з кореневої папки"
echo ""
echo "🔄 Мовні версії:"
echo ""
echo "   UA (Українська) - Стандартна"
echo "   PL (Польська)   - Локалізована"
echo "   EN (English)    - Англійська"
echo ""
echo "📝 Редагування:"
echo ""
echo "   - /ua/index.html для українських текстів"
echo "   - /pl/index.html для польських текстів"
echo "   - /en/index.html для англійських текстів"
echo "   - styles.css для змін стилів (для всіх)"
echo ""
echo "✨ Готово до запуску!"
echo ""
